version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: christophwurst/diesel-cli:latest
    command: [bash, -c, "diesel setup && diesel migration run"]
    volumes:
      - ./:/root/app
    working_dir: /root/app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/athena
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  service:
    build: ./
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/athena
    depends_on:
      migration:
        condition: service_completed_successfully
