on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  docker_build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run the stack
        run: docker-compose up -d
      - name: Test
        run: curl -s localhost:8080/athena/v1/authors | jq
